[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "c-sharp-ref-finder"
version = "0.0.1"
dependencies = [
    "tree-sitter",
    "tree-sitter-c-sharp"
]
